services:
  zero:
    image: dgraph/dgraph:v20.11.3
    container_name: dgraph_zero
    volumes:
      - ./dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:v20.11.3
    container_name: dgraph_alpha
    volumes:
      - ./dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --whitelist 0.0.0.0/0
  ratel:
    image: dgraph/dgraph:v20.11.3
    container_name: dgraph_ratel
    ports:
      - 8000:8000
    command: dgraph-ratel
